baseurl = "https://alosarjos.github.io"
languageCode = "en-us"
theme = "stack"
paginate = 5
title = "AlosarBlog"
disqusShortname = "stack" 
DefaultContentLanguage = "en"

[permalinks]
    post = "/posts/:slug/"
    page = "/:slug/"
    
[params]
    mainSections = ["post"]
    featuredImageField = "image"
    rssFullContent = true
    
    [params.dateFormat]
        published = "January 02, 2006"
        lastUpdated = "January 02, 2006"
        
    [params.sidebar]
        emoji = "🚀"
        avatar = "img/avatar.png"
        subtitle = "Blog for the long journey ahead."
        
    [params.article]
        math = false
        [params.article.license]
            enabled = false 
            default = "Licensed under CC BY-NC-SA 4.0"
            
    [params.comments]
        enabled = false
        provider = "disqus"         # Available: disqus, utterances    
        [params.comments.utterances]
            repo = ""
            issueTerm = "pathname"
            label = ""             # Optional
            theme = "preferred-color-scheme"
            
    [params.widgets]
        enabled = ['archives']
        [params.widgets.archives]
            limit = 5
            ### Archives page relative URL
            path = "archives"     
            
    [params.opengraph]
        [params.opengraph.twitter]
            site = ""
            card = "summary_large_image"
            
    [params.defaultImage]
        [params.defaultImage.opengraph]
            enabled = false
            local = false
            src = ""
            
[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = -100
        pre = "home"
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "about"
        weight = -90
        pre = "user"
    [[menu.main]]
        identifier = "archives"
        name = "Archives"
        url = "archives"
        weight = -70
        pre = "archives"

[related]
    includeNewer = true
    threshold = 60
    toLower = false

    [[related.indices]]
        name = "tags"
        weight = 100

    [[related.indices]]
        name = "categories"
        weight = 200

[markup]
    [markup.highlight]
        noClasses = false